spring.application.name=ToDo-list
spring.datasource.url=jdbc:mysql://localhost:3306/todo_list
spring.datasource.username=root
spring.datasource.password=Segunda3308!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
